### ISSUE TITLE
Connected Component

### ISSUE THREAD

**Issue by jaeseok-huh** [kaist-cp/cs500-2019s#10]
> Definition 5.21 (Connected Component). Let G = (V, E) be an undirected graph. A sub-
graph H of G is a connected component of G if it is a maximally connected subgraph of G.
Here, “maximally connected component” means we ***cannot add any more vertices and
edges from G to H without disconnecting H***.  

I'm having a difficulty to understand the highlighted part. Would you help me to get the meaning, possibly referring to the example below?  
  
![example](https://i.ibb.co/SfZj3Bk/Screen-Shot-2019-03-15-at-12-05-04.png)

Thank you in advance.

**Comment by jeehoonkang** [comment]
Consider the subgraph with vertices {a,b,c,d} and all the edges connecting among them in Graph 2, say H.  If you add to H any vertices and edges, say {e,f} and the edge between them, then the resulting graph (the entire Graph 2) is disconnected.  So H is a maximally connected component.

On the other hand, consider the subgraph with vertices {a,b,c} and edges {{a,b}, {a,c}} in Graph 2, say H'.  Then if we add to H' vertices {d} and edges {{c,d},{b,d}}, then the resulting graph, which is H, is connected.  So H' is not a maximally connected component.

**Comment by jaeseok-huh** [comment]
Thank you @jeehoonkang!
