### ISSUE TITLE
11.5 Substitution Method

### ISSUE THREAD

**Issue by jaeseok-huh** [kaist-cp/cs500-2019s#12]
In the proofs in the book (page 96-97), they just come up with some expressions like, seemingly from nowhere.

Let κ1 =2k and κ2 =k
Let κ = 1/(1-1/2^ε) ·k

How can we pick a value for the recurrence as above?

**Comment by jeehoonkang** [comment]
As discussed in the lecture, inductive invariants are magically given from heaven: you need to find it by trial-and-error.  There are a few heuristics to find them, but all heuristics are by nature not reliable.

For example, you can try (κ1,κ2) = (k,k), and you will fail to finish the proof.  The reason why is the coefficient κ1 for n is less than necessary.  So you can retry with (κ1,κ2) = (2k,k), which will lead us to a qed.
