### ISSUE TITLE
Tree method mergesort

### ISSUE THREAD

**Issue by HaritzPuerto** [kaist-cp/cs500-2019s#15]
Hello,

I have a question about the tree method in the example of mergesort.
![image](https://user-images.githubusercontent.com/2658728/54662354-1633ac80-4b21-11e9-84dc-a6ff72562707.png)

I do not understand how we obtain that sequence (n+n/2+ ... +1)
I know that given a tree with n nodes, its height is O(log n) and I also understand how we obtain the first line of this screenshot.

Thank you

**Comment by jeehoonkang** [comment]
Suppose n is a power of 2.

- for i=0, the second term is c_2 * (1).
- for i=1, the second term is c_2 * (2).
- ...
- for i=lg n - 2, the second term is c_2 * (2^(lg n - 2)) = c_2 * (n / 4).
- for i=lg n - 1, the second term is c_2 * (2^(lg n - 1)) = c_2 * (n / 2).
- for i=lg n, the second term is c_2 * (2^(lg n)) = c_2 * n.

Thus the summation of the second terms is c_2 * (n + n/2 + ... + 4 + 2 + 1).

**Comment by HaritzPuerto** [comment]
Thank you for your fast response! Now it is clear :)
