### ISSUE TITLE
Question about Quiz's problem 5

### ISSUE THREAD

**Issue by qkrclrl701** [kaist-cp/cs500-2019s#16]
Hello, as I remember, I think the problem 5 of the quiz 1 was re-defining Depth, Height, IsLeaf for "undirected" rooted tree which are defined in the textbook for "directed" rooted tree only. However, in the Quiz file that is uploaded, there's no such condition specifying the tree is undirected. Is it just me remembering wrongly, or is the condition missing in the uploaded Quiz file?

Thanks in advance.

**Comment by jaeseok-huh** [comment]
Plus, I think the depth of the root was defined as 0, not 1.

**Comment by jeehoonkang** [comment]
I am sincerely sorry about that.  I updated the file: https://github.com/kaist-cp/cs500-2019s/blob/master/background/quiz.tex

IMPORTANT: please use the updated template for the homework.

**Comment by CauchyComplete** [comment]
So just the statement of the problem 5 has been changed right?

**Comment by jeehoonkang** [comment]
@CauchyComplete Yeah, please see the diff: https://github.com/kaist-cp/cs500-2019s/commit/6953a0cff38a1fc854a8867917c40ac9b4393edd  The quiz was conducted with the updated version.

**Comment by jeehoonkang** [comment]
Closing, as this issue was discussed in class today.
