### ISSUE TITLE
Mathematica series in the exam

### ISSUE THREAD

**Issue by HaritzPuerto** [kaist-cp/cs500-2019s#17]
Hello,

I would like to ask if we need to memorize mathematical series for the exam or if we are given things like this is in the exam.
![image](https://user-images.githubusercontent.com/2658728/54874600-e8f14200-4e31-11e9-9ba0-d09cd028c231.png)

Thank you

**Comment by jeehoonkang** [comment]
I assume you memorize it in the exam, as it's from high school mathematics.

(Btw, the inequality doesn't seem to hold all the time.  Consider the case that a=1.1 and n=100.)

**Comment by HaritzPuerto** [comment]
Then, is it possible to have a list of mathematical series that we need to know? I don't remember all of them...

Thank you

**Comment by jeehoonkang** [comment]
@HaritzPuerto At this moment, the only thing I can say is that as far as you understand the textbook contents, you will understand all the problems and the solutions for the exam.  Sorry to be elusive, but it's the best answer I can have for now.

**Comment by jeehoonkang** [comment]
Closing, as I think the discussion had been settled.
