### ISSUE TITLE
Implementation of update

### ISSUE THREAD

**Issue by HaritzPuerto** [kaist-cp/cs500-2019s#18]
Hello,

The implementation of update is this one:
![image](https://user-images.githubusercontent.com/2658728/55075793-34784a00-50d7-11e9-8900-841d7d487f8f.png)

But according to the definition of update, i is the location to be updated, so I think there is a typo on the implementation and should be change by a[j]. In addition, it looks to me that j is iterating from 0 to |a-1|. Am I right or am I misunderstanding something? Thank you

![image](https://user-images.githubusercontent.com/2658728/55075934-84efa780-50d7-11e9-829c-36a39a05a28c.png)

**Comment by jeehoonkang** [comment]
- You're right in that "a[i]" should be "a[j]".
- According to the Example 13.5, "j" is iterating from 0 to |a|-1, as you said.

**Comment by HaritzPuerto** [comment]
Thank you
