### ISSUE TITLE
[question] solution for the quiz

### ISSUE THREAD

**Issue by justin-labry** [kaist-cp/cs500-2019s#19]
Hi, Professor,

It would be very helpful if you could share with us the solution tex file to compare with our own answers and study further on our own.

I wrote down the answers in class, but the tex file would help me a lot to double-check my answers and figure out some non-critical syntax errors (Overleaf).
 
Thank you so much.

**Comment by thaodod** [comment]
Yes, I think Professor @jeehoonkang should give classes some kind of exercises or non-graded assignments to let us practice and know what we gonna face in quiz or midterm/ final term. I honestly worry about that whenever recall the first quiz with a lot of surprising.

**Comment by jeehoonkang** [comment]
- @justin-labry @doduythao you can just call me @jeehoonkang here.
- @justin-labry I'll soon share the solution latex file.
- @doduythao yeah, one of the purposes of the quiz was preparing the students for the exam.  I believe you all kinda understood what's my style, but need more.  I'll soon give you a study guide for the midterm exam.

**Comment by justin-labry** [comment]
@jeehoonkang I’d appreciate it!
