### ISSUE TITLE
Question about quiz solution

### ISSUE THREAD

**Issue by anonymous-3567** [kaist-cp/cs500-2019s#25]
![image](https://user-images.githubusercontent.com/32038046/55860958-4b776b80-5bb0-11e9-80d6-fd1da0c169bf.png)
In the quiz solution, defines Height as Minimum of Depth(G, v_0, v).
I think it should be change into Maximum. Is it right? or my mistake. Thanks!

**Comment by thaodod** [comment]
Yup. Professor might forget it. He once said that. Height here is the length of "longest" arm of the tree.

**Comment by anonymous-3567** [comment]
Thanks!
