### ISSUE TITLE
Dijsktra's Algorithm Proof X' intersection F'

### ISSUE THREAD

**Issue by HaritzPuerto** [kaist-cp/cs500-2019s#27]
Hello,
The first condition we have is 
![image](https://user-images.githubusercontent.com/2658728/55936699-ff8cfb00-5c71-11e9-8694-b29f8908e6cc.png)

However, in the inductive case, we don't have an intersection but a union. Is it a typo?
![image](https://user-images.githubusercontent.com/2658728/55936685-f2700c00-5c71-11e9-90a5-f6b5016fd862.png)
Actually, the union of two non-empty sets cannot be empty, right?

Thank you

**Comment by jeehoonkang** [comment]
Thanks for pointing out the bug.  I just fixed it.
