### ISSUE TITLE
search algorithm pdf file

### ISSUE THREAD

**Issue by guldampotentard** [kaist-cp/cs500-2019s#29]
why don't you upload pdf-compiled file for the search algorithm lecture notes?

**Comment by thaodod** [comment]
Binary file is not native (first priority) on git system and also I guess our professor wants us to use/practice latex (which is beneficial for writing scientific document/publication later).

**Comment by hyunsoo0o0o0** [comment]
I mostly use mobile device when I read something, so it will be great if .pdf is uploaded as well. I agree that dealing with  LaTeX is a great skill, but lack of compiled document feels less accessible..

**Comment by HaritzPuerto** [comment]
You can just copy and paste the code on https://www.overleaf.com and compile it. It will take less than 5 minutes and you don't need to install anything

**Comment by jeehoonkang** [comment]
I'm uploading the pdf here, but please note that it can be updated in the future: [search-algorithms.pdf](https://github.com/kaist-cp/cs500-2019s/files/3071509/search-algorithms.pdf)
