### ISSUE TITLE
Asking about recurrence problems in exam

### ISSUE THREAD

**Issue by giangnguyen2412** [kaist-cp/cs500-2019s#34]
Dear Professor @jeehoonkang ,

In recurrence problems, I see that they are always easily addressed by using Brick method no matter what kind of problems are (root, leave dominated or balanced - `*if I am correct*`), so in the exam, could we choose arbitrarily which method to be used?

And another question, will substitution method and master method be covered in the exam as you just swiftly mentioned about them in the class.

Thank you for your time.

**Comment by thaodod** [comment]
I found on the note (recurrence tex) also written that we're free to use any method except the question clearly request that we have to use specified method.

**Comment by jeehoonkang** [comment]
@doduythao answered your question for me :)

**Comment by giangnguyen2412** [comment]
@jeehoonkang How about the second question?
