### ISSUE TITLE
Question about asymptotic complexity proof by induction 

### ISSUE THREAD

**Issue by hieudz** [kaist-cp/cs500-2019s#36]
My question is: Why do we need to add constant when considering the big-O notation?

For example in the induction proof of W(n) = W(n/2) + O(n) = O(n). By definition, we only need to find a function that in form of a * n which is greater than W(n) as n goes to infinity. Why don't we just replace the term O(n) in first equation with c1*n? Then the proof will be much easier when we try to prove W(n) ⩽ 2 * c1 * n:

W(n) = W(n/2) + O(n) ⩽ W(n/2) + c1 * n ⩽ 2 * c1 * (n/2) + c1 * n = 2 * c1 *  n

![image](https://user-images.githubusercontent.com/28869165/56037845-4ca0c800-5d6b-11e9-93dd-6c8c64b60017.png)

**Comment by jeehoonkang** [comment]
Yes, you're right.  But for other problems, adding the constant `c2` actually makes it easier to solve.  I added `c2` for all solutions for consistency.
