### ISSUE TITLE
[announcement] Quiz on Part I: Background on March, 18th

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs500-2019s#4]
We will have a quiz on March, 18th (20 minutes at the beginning of the lecture).  The quiz is about the textbook's Part I: Background.

**Comment by CauchyComplete** [comment]
It seems that there is no Part II: Background in the textbook. You mean Ch. 4~5 ?

**Comment by HaritzPuerto** [comment]
Hello,
According to the website, part 2 is ch 4 and 5
https://sites.google.com/view/algorithms-book/ @CauchyComplete

**Comment by jeehoonkang** [comment]
Sorry for the confusion.

- We'll use the complete book (https://sites.google.com/view/algorithms-book/) as the reference.
- The quiz will be on Part I: Background, from page 31 to page 46.
