### ISSUE TITLE
Question abour BFS when using sorted index sequence

### ISSUE THREAD

**Issue by qkrclrl701** [kaist-cp/cs500-2019s#40]
![20190413_213808](https://user-images.githubusercontent.com/30802922/56079825-8093f000-5e34-11e9-8f47-4489d5eaa2c0.jpg)

The above figure is from the previous answer.

I wonder why N_G(F) costs O(|N_G(F)|log|F|) work and O(log^2|F|) span.

I think, since merge A B has O(|A|+||B|) work
and O(log(|A|+|B|)) span, N_G(F) costs differently. 
(I'm not sure, bit maybe O(|N_G(F)|×|F|) work and O(log(|N_G(F)|×log|F|) span.

Plus, do we need to study about the work efficient merge algorithm that has O(logN) span?

**Comment by jeehoonkang** [comment]
- Please leave your question as a reply to the original thread.  (Closing this issue.)
- I'll revisit this topic after the midterm exam.  You can be sure that the cost analysis of BFS will not be asked in the exam.
- I cannot precisely answer questions on the coverage of the exam.  Sorry.
