### ISSUE TITLE
Mattermost invitation

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs500-2019s#44]
https://cp.kaist.ac.kr/mm/signup_user_complete/?id=jbrjpkhjepn6dd4azno4i1brwo

**Comment by thaodod** [comment]
There is no verification email sent. Can you check it ?

**Comment by jaeseok-huh** [comment]
I've not got that either, with two different email domain--kaist.ac.kr & gmail.com.

**Comment by jeehoonkang** [comment]
Thank you for pointing out the issue.  Prooobably the issue is fixed as of now.
