### ISSUE TITLE
[Systloic Array] What is n?

### ISSUE THREAD

**Issue by HaritzPuerto** [kaist-cp/cs500-2019s#46]
Hello,

I would like to know what n is in the line 8 of the systolic array algorithm.

Thank you

**Comment by giangnguyen2412** [comment]
It should be the size of the square matrix `nxn`.

**Comment by jeehoonkang** [comment]
@luulinh90s you're right---thanks for answering the question.

**Comment by HaritzPuerto** [comment]
Hi, sorry for the late reply. Why square matrix? In the videos, there is no square matrix
Thank you

**Comment by giangnguyen2412** [comment]
Hi, 

I think square matrix is used to ease the cost and span analysis. Actually, we can freely use Systolic array for matrix multiplication. When the matrix is not square, the cost and span will be a bit odd, so it doesn't matter when you still ultimately get the same cost and span for Matrix Multiplication.
