### ISSUE TITLE
Lemma of odd-even sort

### ISSUE THREAD

**Issue by giangnguyen2412** [kaist-cp/cs500-2019s#49]
Hi,

I wanna ask about the lemma 1 of odd-even sort algorithm.
Here for both odd and even arrays, we are supposing `∃j s.t `:

`AOj` <= `COi` <= `AOj+1`.

Here, I wanna clarify what is `i` and what is the relation between `i` and `j`.

Thank you.

**Comment by HaritzPuerto** [comment]
I think for all i there is j such that `AOj <= COi <= AOj+1`

**Comment by jeehoonkang** [comment]
Yeah, for all i, there *exists* j such that ...
