### ISSUE TITLE
[announcement] Midterm & final exam on April, 15th and June, 10th

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs500-2019s#5]
As announced in the [Syllabus](https://cais.kaist.ac.kr/syllabusInfo?year=2019&term=1&subject_no=36.500&lecture_class=%20%20&dept_id=4421) and the [KAIST Academic Calendar](http://www.kaist.edu/_prog/adcal/?dvs_cd=1&site_dvs_cd=en&menu_dvs_cd=03030101), the midterm and final exam will be on:

- Midterm: April, 15th 09:00am-11:45am
- Final: June, 10th 09:00am-11:45am

**Comment by jeehoonkang** [comment]
Until today, I didn't know there are about 70 students in this class :)  See you guys all in the exams!

**Comment by jeehoonkang** [comment]
You folks can write Korean or English in your answer sheet.

**Comment by jeehoonkang** [comment]
For the exam, you need to bring your student ID card or any certificate of studentship.

**Comment by ghost** [comment]
where is the location?

**Comment by jeehoonkang** [comment]
@guldam1234 The same place: Rm 403, E11.

**Comment by Dr-zzt** [comment]
Is there any tentative plan for claims? My concern is that I have to attend MobiSys 2019, which is going to take place next week. (I'll be in Seoul from 6/16 to 6/21) I'm afraid I won't be able to attend the claim session...

**Comment by jeehoonkang** [comment]
@Dr-zzt I'm grading the submissions, but I don't think it'll be finished this week..  Sorry.  If you need to claim, please contact me via email.
