### ISSUE TITLE
Lecture notes

### ISSUE THREAD

**Issue by doxuanviet1996** [kaist-cp/cs500-2019s#53]
Professor, can you please upload the lecture notes of what we have been learning so far since midterm?
Final is coming, and we would really need materials to revise on.

**Comment by jeehoonkang** [comment]
Sure.  I'll upload the lecture note by the next Monday.

**Comment by jeehoonkang** [comment]
- I merged all the lecture note here: https://github.com/kaist-cp/cs500-2019s/blob/master/lecture-note/lecture-note.tex
- The slides for concurrent algorithms here here: https://github.com/kaist-cp/cs500-2019s/blob/master/concurrent-algorithms.pdf
- What's missing in the lecture note is odd-even merge sort, bitonic sort, and dynamic scheduling.  I'll fill them out by the next Monday.

**Comment by jeehoonkang** [comment]
The lecture note is now fully updated:
- https://github.com/kaist-cp/cs500-2019s/blob/master/lecture-note/lecture-note.tex
- https://github.com/kaist-cp/cs500-2019s/blob/master/concurrent-algorithms.pdf
