### ISSUE TITLE
Coverage of final exams?

### ISSUE THREAD

**Issue by fairy-of-9** [kaist-cp/cs500-2019s#54]
Hi,

I think, final exam covers all class materials after midterm. right?
Could you announce the coverage of the final exam?

thanks.

**Comment by jeehoonkang** [comment]
After the midterm, we studied:

- graph algorithms (the remaining part)
- Brent's theorem
- Systolic array
- Odd-even merge sort
- Bitonic merge sort
- Dynamic scheduling
- Concurrent algorithms

We will cover all of them in the final.

**Comment by fairy-of-9** [comment]
Thank you!
