### ISSUE TITLE
Update the score of midterm after claim on KLMS

### ISSUE THREAD

**Issue by giangnguyen2412** [kaist-cp/cs500-2019s#55]
Dear Professor,

Could you tell us when you will update the score of midterm exam? 

Thank you.

**Comment by Dr-zzt** [comment]
Same here. Can you check my midterm points as well? (My student # is 20184358)

**Comment by JibonNaher** [comment]
Same for me. Can you please check mine too? (ID: 20184619)

**Comment by jeehoonkang** [comment]
I will reflect the claims after the final exam.  I have data in a spreadsheet, and copying it to KLMS is a laborious task...  Will do it once and for all after the final.

(Please keep this issue open so that I can track this issue.)

**Comment by jeehoonkang** [comment]
I updated it.  If your scores are not updated yet, please kindly inform me.
