### ISSUE TITLE
Question about the index in systolic array

### ISSUE THREAD

**Issue by BoSamothrace** [kaist-cp/cs500-2019s#56]
When we calculate the output O, the algorithm is (i,k-n-i) to A(i,n-1). 
I am a little confusing about this. I know k start from 0, then there is some conflict with n. 
I assume n equal to 3 if we have 3by3 matrix. Then I think (i,k-n+1-i) to A(i,n-1) might be better. 
If n equal to 2 for 3by3 matrix, maybe the algorithm should be (i,k-n-i) to A(i,n)

Anyone could help me?

**Comment by CauchyComplete** [comment]
I think the code is right since there were no errors when I implemented it. Both for n=2 and n=3.

**Comment by jeehoonkang** [comment]
@CauchyComplete may I ask if you could explain the algorithm in more details?

**Comment by CauchyComplete** [comment]
@jeehoonkang I don't understand your question. I just used the algorithm in the lecture note!

**Comment by jeehoonkang** [comment]
@BoyOfSamothrace I also think the code is right...  May I ask if you could implement it and see what happens?

**Comment by thaodod** [comment]
I think the problem the OP saying is that when K=0 and j=1 --> out of range. In my case, I just let it be 0.

**Comment by BoSamothrace** [comment]
Let's say there are 3by3 matrixes W and X. (n=3)
At the third invocation of SystolicInner (k=2), we could get the first result which should be O(0,0)=A(0,2). Be aware now the k=2 and n=3.
Based on the algorithm, O(i,k-n-i) will be O(0,-1). 
I just think the index k and n couldn't match here.

I could try to implement it after the exam. I am a little busy these days ㅠㅠ

**Comment by BoSamothrace** [comment]
Sorry. I mistakenly read A(i,n-1) as A'(i,n-1).
