### ISSUE TITLE
typo in lecture note

### ISSUE THREAD

**Issue by jihoon-ko** [kaist-cp/cs500-2019s#59]
1. (Systolic Array) output is WX'
2. (Spinlock) condition in spinlock::lock has problem

**Comment by jeehoonkang** [comment]
Thank for reporting this!

**Comment by giangnguyen2412** [comment]
which condition in spinlock has problem? I dont see the professor modify any

**Comment by jeehoonkang** [comment]
Removal of `!` in lock()
