### ISSUE TITLE
Have question in p18 of concurrent algorithm

### ISSUE THREAD

**Issue by SeongJinAhn** [kaist-cp/cs500-2019s#67]
In p18 it is said that X.load(acquire) disallows hoisting of later instruction.
But in p19 lock.swap(true,acquire) is written tosolve problem of spinlock rather than lock.load(true,acquire).
Is it right? If then could you tell me the reason?

**Comment by jeehoonkang** [comment]
`swap` performs read and write at the same time.  The `acquire` annotation in `swap()` also means it disallows hoisting of later instructions.

**Comment by jeehoonkang** [comment]
(Closing, as it seems @SeongJinAhn acknowledged my answer.  Feel free to reopen it!)
