### ISSUE TITLE
Codes of systolic array, odd-even sort, and bitonic sort

### ISSUE THREAD

**Issue by hyunsoo0o0o0** [kaist-cp/cs500-2019s#71]
https://gist.github.com/ppnchb/33cf1bbf0bea325f1a2b3998af971bd4

I tried to implement these 3 algorithms with python and here's the result.
Systolic array is just a direct translation from pseudocode in the lecture note to python, and others are added with proper sort algorithm using given merge algorithm in the lecture note.
I think it works OK, but who knows. If you find any mistake, please share.
I hope it can give you better understanding on course materials, as I did while writing.

**Comment by BoSamothrace** [comment]
Ohhh. Thank you very much~

**Comment by jeehoonkang** [comment]
Thank you so much.  Your contribution is invaluable to us all.  May I ask if I can use the code for the next semesters?

**Comment by hyunsoo0o0o0** [comment]
@jeehoonkang Sure!

**Comment by CauchyComplete** [comment]
Wow `I[0,j] = X[k-j, j] if 0 <= k - j < l else 0` I didn't know this works

**Comment by jeehoonkang** [comment]
At this stage of the semester, I'd like to close tech-related issues.
