### ISSUE TITLE
Release/Acquire instructions for Concurrent Linked List

### ISSUE THREAD

**Issue by HaritzPuerto** [kaist-cp/cs500-2019s#73]
Hi,

In the slides, it is written that we use release and acquire operations to access a node's next pointer. However, in the code we wrote in class, we did not use release and acquire. In addition, it is also written that all operations are tolerant to reordering thanks to release and acquire. So do we use implicitly release and acquire in all operations?

Thanks

![image](https://user-images.githubusercontent.com/2658728/59154857-eb6d4a80-8ab6-11e9-9dfb-03e0be682039.png)

**Comment by jeehoonkang** [comment]
@HaritzPuerto Yes, we assume all load/store to shared locations in linked list are release/acquire.

**Comment by HaritzPuerto** [comment]
thank you for the clarification :)
