### ISSUE TITLE
Question about linked list

### ISSUE THREAD

**Issue by kuonom** [kaist-cp/cs500-2019s#76]
in list X->Y->Z->W,
like pdf, when we delete Z and insert N between Z and W, if insert is aborted, you said insert will retry. then what's mean of "retry"?

if don't execute insertion, result will be X->Y->W.
what's happen if insertion is retry? it can be X->Y->N->W? I think it is not good..

**Comment by jeehoonkang** [comment]
At this stage of semester, I'd like to close tech-related issues.
