### ISSUE TITLE
Final exam scores/claims and letter grades

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs500-2019s#79]
- Now you can check your final exam scores in KLMS.  The highest score is 97, and every problem is fully solved by at least one student.  Here is the [histogram](https://docs.google.com/spreadsheets/d/e/2PACX-1vQ_Pxi-XKUylWqN2OUgAfzT2aRobQfnVV22sEpY99D57r4EvxMeuQvKUvZ4_4hhoD6V1regIQiGuwRg/pubchart?oid=195117407&format=interactive).

- I uploaded the letter grades to KAIST portal systems.  Here is the [histogram](https://docs.google.com/spreadsheets/d/e/2PACX-1vQ_Pxi-XKUylWqN2OUgAfzT2aRobQfnVV22sEpY99D57r4EvxMeuQvKUvZ4_4hhoD6V1regIQiGuwRg/pubchart?oid=776374243&format=interactive) for (midterm score + final score).

- You can claim on the final exam scores in 10am-11am, 26-28th, June.  **Please send me an email to make an appointment, first.**

- If you think I made any mistakes in grading, please send me an email by 27th, June.

**Comment by giangnguyen2412** [comment]
How can I see my letter grade. Thank you.

**Comment by thaodod** [comment]
It's on KLMS, (same method as midterm result announcement), open the notification.

**Comment by giangnguyen2412** [comment]
Where is my letter grade (A or B ...)? not final score.

**Comment by jeehoonkang** [comment]
Hmm..  I input the scores, but I don't know how to check them as a student.  Would anyone please help us..?

**Comment by giangnguyen2412** [comment]
You said that `I uploaded the letter grades to KAIST portal systems.` But I dont see the letter grades, just see the score..

**Comment by CauchyComplete** [comment]
It will be visible at today midnight as far as I know

**Comment by giangnguyen2412** [comment]
Ah ha, I see :)

**Comment by giangnguyen2412** [comment]
The preview session will start from today midnight...

**Comment by jeehoonkang** [comment]
- I reflected all the additional points you've earned in claims.
- I changed the criteria for the letter grades.  As a result, some of the students whose original grades were B- or lower, were given a better one.

I'm finalizing the grading.  Thank you for taking this course!
