### ISSUE TITLE
Definition Paths(G)

### ISSUE THREAD

**Issue by HaritzPuerto** [kaist-cp/cs500-2019s#8]
![image](https://user-images.githubusercontent.com/2658728/54079518-4ad58600-4321-11e9-92de-ff266b28292f.png)

Hello,
I understand what the set of all paths is, but I don't understand the mathematical definition provided by the book.
V+ is the set of all positive length sequences of vertices. First, I find this weird because of the word positive. How is it possible to have a negative length? If we had weighted graphs, it would be possible, but weighted graphs are defined later, so at this point we cannot have negative lengths, right? Furthermore, if V+ has sequences of vertices, (Pi, Pi+1) cannot belong to the set of edges, because Pi is not a vertex but a sequence of vertices.

Thank you

**Comment by JibonNaher** [comment]
I think, here, positive does not have anything with weight. From previous contexts, it may mean outdegree vertices (I mean, the endpoint vertices of an edge). And for the latter part, I think it means that every P(path) is also edge. The latter part is confusing actually.

**Comment by jeehoonkang** [comment]
I believe it's for ruling out sequences of length zero.

**Comment by HaritzPuerto** [comment]
I see. Then, what is Pi? A sequence of vertices or just a vertex?

Thank you

**Comment by jaeseok-huh** [comment]
@HaritzPuerto a vertex. P is a (positive length) sequence of vertices, being the element of V+.

**Comment by HaritzPuerto** [comment]
Thank you, now I got it
