### ISSUE TITLE
Mapping in relations

### ISSUE THREAD

**Issue by giangnguyen2412** [kaist-cp/cs500-2019s#9]
![relation1](https://user-images.githubusercontent.com/30857111/54338150-6966b480-4674-11e9-9d9c-a99b22b6020e.JPG)

When reading `example 4.4`, set Y is defined as `Y = {(0, a), (1, b), (3, a)}`
is both a relation and a function from A to B since each element only appears once on the
left. At this time, `|R| = 3`.

However, `domain(R) = A = {0, 1, 2, 3}`, so `|domain(R)| = 4`. It is violated from the ***Definition 4.6*** that `|R|` should be equal to `|domain(R)|`.

Could someone clarify this? Thank you.

**Comment by jeehoonkang** [comment]
Definition 4.5 says the domain of `Y` is `{a: (a,b) \in Y} = {0, 1, 3}`.  Thus `|domain(Y)| = 3 = |Y|`.

It is worth noting that Definitions 4.5 and 4.6 are nonstandard in that e.g. the "function" defined in Definition 4.6 is usually called "partial function" in other Mathematics textbooks.  So in the quiz, I will not ask questions for which you need to distinguish functions and partial functions precisely.

**Comment by giangnguyen2412** [comment]
I got it, and I think this point is confusing without explanation of partial function and function.
Thank you.
